### ISSUE TITLE
Kings day in the Netherlands

### ISSUE THREAD

**Issue by shizawana** [svendiedrichsen/jollyday#10]
The Kings birthday in the Netherlands is celebrated on the 27th of April, except when this falls on a Sunday and it is celebrated on the Saturday instead.

It should be:
    `<tns:Fixed month="APRIL" day="27" validFrom="2014" descriptionPropertiesKey="KINGS_DAY">
    <tns:MovingCondition substitute="SUNDAY" with="PREVIOUS" weekday="SATURDAY"/>
    </tns:Fixed>`

**Comment by svendiedrichsen** [comment]
Fixed. Thanks for the info.
