### ISSUE TITLE
Multiple HolidayManager objects using different Holiday sources

### ISSUE THREAD

**Issue by Netskeh** [svendiedrichsen/jollyday#102]
Hey,

I was wondering if it is possible to have 2 (or more) different HolidayManagers objects. So far I only found the HolidayManager#getInstance(...), which heavily suggests it works as a Singleton. 
My use-case involves taking care of Holidays of different countries (or states depending of the specific country)
Did I miss anything or is jollyday not ready for that just yet?

If multiple objects are not possible, how could I safely change the configuration to do my operations in a sequential fashion?

**Comment by thackel** [comment]
Why do you think you can not create multiple HolidayManagers with
`HolidayManager.getInstance(managerParameter)`?

I am doing this with this method.

**Comment by Netskeh** [comment]
this is awkward. You are absolutely right. The error must be hidden in my facade somewhere...
Thanks your comment gave me the incentive of testing it on a fresh project.

**Comment by Netskeh** [comment]
and a very stupid one at that...
