### ISSUE TITLE
PALM SUNDAY missing?

### ISSUE THREAD

**Issue by mortensimon** [svendiedrichsen/jollyday#106]
Hi, I have checked the Norwegian holidays and can confirm that those are correct, except for the missing Palm Sunday, a week before Easter. I was not able to understand how to add it, since I could not find that day anywhere in any xml. It would be great if it could be added, since it would make Norway holidays complete. Thanks in advance.

**Comment by mohamead** [comment]
Hi @mortensimon,
To my knowledge "Palm Sunday" is not a public holiday in Norway: 
 
Ref -> https://www.timeanddate.com/calendar/?country=18
Ref -> https://www.timeanddate.com/holidays/norway/palm-sunday
Ref -> https://lovdata.no/dokument/NL/lov/1995-02-24-126.91.351062.620576d570

This is the reason why this has not been added..

**Comment by mohamead** [comment]
Hi @mortensimon,
To my knowledge "Palm Sunday" in it self is not a public holiday (red day) in Norway: 
 
Ref -> https://www.timeanddate.com/calendar/?country=18
Ref -> https://www.timeanddate.com/holidays/norway/palm-sunday

This is the reason why this has not been added..

**Comment by mohamead** [comment]
Hi @mortensimon,
To my understanding "Palm Sunday" in it self is not a public holiday (red day). 

Ref -> https://lovdata.no/dokument/NL/lov/1995-02-24-12

**Comment by mortensimon** [comment]
I stand corrected - I agree. Thanks for the great work!
