### ISSUE TITLE
Unofficial holidays

### ISSUE THREAD

**Issue by provincjalc** [svendiedrichsen/jollyday#11]
Hi,

it would be nice if we could check if selected day is holiday and specify weather we would like to check unofficial holidays or not.

Currently:
isHoliday = manager.isHoliday(calendar, countryPrefix);

New:
isHoliday = manager.isHoliday(calendar, countryPrefix, checkUnofficial);

Greating, Rok

**Comment by svendiedrichsen** [comment]
Implemented this feature. You can specify the HolidayType to check for isHoliday. NULL ignores this parameter.
