### ISSUE TITLE
Is there a way to access all State Holidays?

### ISSUE THREAD

**Issue by MartinSchmitzDo** [svendiedrichsen/jollyday#117]
Hi everyone,

is there anyway to access all state holidays of a given country? I would love to do something like

```
ManagerParameter pm = new CalendarPartManagerParameter(countryCode.toLowerCase(), null);
HolidayManager holidayManager = HolidayManager.getInstance(pm);	

for(String state : holidayManager.getSupportedStates()){
    Holiday day = holidayManager.getHolidays(year, state)
}
```

i've not found a way to do this, since there is not such a function like 'getSupportedStates() or so. Did i miss something?

Best,
Martin

**Comment by thackel** [comment]
Use ```holidayManager.getCalendarHierarchy().getChildren()``` which contains the states.
E.g. ```children.getDescription()``` contains the state and its childen all the holidays related to this state.

**Comment by MartinSchmitzDo** [comment]
Thanks, worked like a charm!
