### ISSUE TITLE
Some questions. (want to contribute)

### ISSUE THREAD

**Issue by paul-di** [svendiedrichsen/jollyday#12]
1. Do you have some kind of gui calendar (web for example), backed by your library. It will make more simple to find errors in it
2. Do you concentrate only in holidays that are non-working days?
3. Does your application support short working days (non full working days)
4. Does your application detect every week holidays (saturday + sunday - most of countries, only suturday + short working day at friday - israel)

I want to contribute to russia holidays

**Comment by svendiedrichsen** [comment]
Hi paul-di,
1) I have thought about a web app to manage holidays but haven't found time to start.
2) there is an option to mark holidays as NON_OFFICIAL which is used for non-off holidays
3) the distinction between OFFICIAL and NON_OFFICIAL can be extended for short holidays
4) the API recognises all holidays irrespective if they fall on a weekend. They may have a moving condition if they do fall on a specific weekday

Cheers
Sven

**Comment by svendiedrichsen** [comment]
Hi paul-di,
the first and most important contribution every one would highly appreciate is a proper russian holiday calendar. 
Cheers, Sven
