### ISSUE TITLE
Pfingstsonntag in Germany

### ISSUE THREAD

**Issue by SeriousSem** [svendiedrichsen/jollyday#13]
Hi,

this one should be "Pfingstsonntag" instead of "Pfingssonntag":
[holiday_descriptions_de.properties](https://github.com/svendiedrichsen/jollyday/blob/master/src/main/resources/descriptions/holiday_descriptions_de.properties#L233)

By the way thank you for your work,
Sem.

**Comment by svendiedrichsen** [comment]
Thanks, will fix it.
