### ISSUE TITLE
[question] how to configure advent?

### ISSUE THREAD

**Issue by udo1toni** [svendiedrichsen/jollyday#132]
I'm wondiring how to write the correct configuration for advent:
Fourth Sunday before December, 25.
Third Sunday before December, 25.
Second Sunday before December, 25.
First Sunday before December, 25.

Any hints?

**Comment by svendiedrichsen** [comment]
In my opinion Jollyday is for tracking off-work holidays. German advents aren't holidays and they are always on sunday. Thus they are off-work by definition.

**Comment by int5749** [comment]
That's probably also the reason why easter-sunday is not defined as holiday? Even it's holiday and calculated as this day is required as reference for many other but it's always a sunday.

Nevertheless this action can be used to define othere and question is about defining personal special day, like a birthday etc. Hopefully someone can advise how to go back from a known day to first, sencond, etc sunday before this known date?

**Comment by int5749** [comment]
Hi all,
I looked though many of the holiday Examples as well as through embedded Parser Files.
Finally I made it => FixedWeekdayRelativeToFixed <= this is the right parser for this ;-)
