### ISSUE TITLE
Adjusting Marine/Navy/Sea public holiday in Japan

### ISSUE THREAD

**Issue by xHoang** [svendiedrichsen/jollyday#133]
Currently the code for the marine day JPY holiday is put as June 20th. This is no longer the case and is instead on the third monday of July. How do I implement this functionality into https://github.com/svendiedrichsen/jollyday/blob/master/src/main/resources/holidays/Holidays_jp.xml

Thanks

**Comment by svendiedrichsen** [comment]
@xHoang You could probably do it like this:
`<tns:FixedWeekday which="THIRD" weekday="MONDAY" month="JANUARY" validFrom="1986" descriptionPropertiesKey="MARTIN_LUTHER_KING"/>`

**Comment by svendiedrichsen** [comment]
@xHoang According to Wikipedia the Marine/Navy Day was held from 1996 to 2002 on the 20 of July. From 2003 onwards it was held on the 3rd monday in july. The holidays file already reflects this.
