### ISSUE TITLE
Germany: Reformationstag as one-time public holiday

### ISSUE THREAD

**Issue by jschrod** [svendiedrichsen/jollyday#32]
2017 we will have Reformationstag (2017-10-31) as public holiday in all of Germany, but only that year.
I suppose one has to add a Fixed entry with validFrom and validTo at the top of Holidays_de.xml.
Is this already in the works or do you want a pull request?

Cheers, Joachim

**Comment by svendiedrichsen** [comment]
Would be very nice of you if you could create a pull request for this. Thanks in advance.
Cheers, Sven

**Comment by GeBeater** [comment]
Pull request #34 created.

**Comment by jschrod** [comment]
OK; a pull request within 16 minutes, while I'm watching semifinals; beats me. You're both obviously no football fans. :-) :-)
Thanks a lot, Bernd and Sven!!

**Comment by opensource21** [comment]
Any chance that a new version will be published? We now have 2017 and in 2018 the patch is useless.

**Comment by svendiedrichsen** [comment]
released 0.5.2
