### ISSUE TITLE
Additional holiday in japan

### ISSUE THREAD

**Issue by fanste** [svendiedrichsen/jollyday#44]
I've got the feedback from a japanese colleague that there is a new public holiday in japan.
`<tns:Fixed month="August" day="11" validFrom="2016" descriptionPropertiesKey="Mountain_DAY"/>`

Wikipedia is telling me, that it is valid from 2017. But I think the guy form japan should be right ;)

Is it possible to add it to both versions/branches?

**Comment by svendiedrichsen** [comment]
I will take care of this and it should be possible to add it to both branches.
