### ISSUE TITLE
NullPointerException when loading Configuration

### ISSUE THREAD

**Issue by krichter722** [svendiedrichsen/jollyday#51]
Did you notice https://sourceforge.net/p/jollyday/discussion/1076447/thread/a5c0ac85/?limit=25? It contains a fix which seems to be working well, but wasn't merged for > 6 months.

Issues should be handled in one place only. The most recent activities seems to be on github.com currently.

**Comment by svendiedrichsen** [comment]
Classloading has just been redone. Please check out the current SNAPSHOT version.

**Comment by krichter722** [comment]
> Classloading has just been redone. Please check out the current SNAPSHOT version.

I can confirm that the issue is fixed in v_0_5_2-27-ged7f922 (possibly earlier). I made a mistake with Maven's exclusion mechanism.

Consider doing something about the two issue trackers, although it's not the place to discuss this.

**Comment by svendiedrichsen** [comment]
I will. Thanks for testing.
