### ISSUE TITLE
Where is the package "de.jollyday.config" on GitHub?

### ISSUE THREAD

**Issue by MenoData** [svendiedrichsen/jollyday#59]
Some classes like `EthiopianOrthodoxHolidayParser` refer to the package (for example to the class `de.jollyday.config.Holidays`) but I cannot find the package - neither on GitHub nor on downloaded zip-files from GitHub. I think, an open-source-project is supposed to contain all source code, or have I overlooked something?

Background is, I would like to contribute for example Hebrew holidays in the future but then I need to see and understand the whole source code...

**Comment by MenoData** [comment]
Okay, it is dynamically created via xml-binding but I still see the disadvantage not to have reasonable good javadocs and source code navigation.

**Comment by svendiedrichsen** [comment]
Classes under `de.jollyday.config` don't contain any logic. They are simple DTO classes which are used by JAXB for deserializing XML files.  They only carry generated javadoc and anntotations and will never be checked in as normal source code is. Including these into generated javadoc will not provide any insight into how the API work but will distract from working code.

**Comment by MenoData** [comment]
I see your point. So that package is some kind of implementation internals. But I also still see the problem that other parts of public API refer to the package `de.jollyday.config`, for example: 

http://jollyday.sourceforge.net/apidocs/de/jollyday/util/CalendarUtil.html#create-int-de.jollyday.config.Fixed-

IMHO, a public API should not refer to internals. This has first made it difficult for me to understand your API, and introducing new public interfaces might solve the problem, but of course, you are free to close this issue without action if it is too much work for you.

**Comment by svendiedrichsen** [comment]
I'm open to any suggestions. Please feel free to fork and rework apropriately.

**Comment by MenoData** [comment]
Okay, I will try to make some proposals in code form later (but probably rather in the begin of year 2018 when I can also contribute holidays in Israel).

**Comment by MenoData** [comment]
By the way, have you noticed that Oracle seems to be willing to delete the `javax.xml.bind`-package from JDK? Java-9 has this information about the associated module:

```
@Deprecated(since="9", forRemoval=true) 
Module java.xml.bind
```

Here an official link: http://openjdk.java.net/jeps/320

It would probably affect Jollyday so I thought it is good for you to know for the future.

**Comment by svendiedrichsen** [comment]
Thank you. Good to know.
