### ISSUE TITLE
Custom Holidays

### ISSUE THREAD

**Issue by someshjainiitkgp** [svendiedrichsen/jollyday#63]
Hi,
  I am able to load my custom holidays, but it's not able to read the decription as the corresponding keys don't exist in holiday_descriptions.properties. I've provided the key in my custom properties but that doesn't seem to work either 

```
  def getConfig(): HolidayManager = {
    val urlOpt = Some(getClass.getClassLoader.getResource("holidays.xml"))
    urlOpt match {
      case Some(url : URL) =>
        val props = new Properties()
        props.put("holiday.description.OATH_BIRTHDAY", "oath birthday")
        val urlManParam = new UrlManagerParameter(url, props)
        HolidayManager.getInstance(urlManParam)
      case _ =>
        HolidayManager.getInstance()
    }

```

**Comment by svendiedrichsen** [comment]
@someshjainiitkgp I'm afraid but there is currently no way to add new descriptions like you can add new holiday files.
