### ISSUE TITLE
NL Calendar - Good Friday is not a public holiday

### ISSUE THREAD

**Issue by Philipp-Borchert-ISH** [svendiedrichsen/jollyday#69]
Current behavior: 
HolidayManager.isHoliday(LocalDate.of(2018, 3, 30), HolidayType.OFFICIAL_HOLIDAY); returns true for the Netherlands HolidayCalendar

Expected behavior:
It should return false, Good Friday is not an offical public holiday in the Netherlands - see https://en.wikipedia.org/wiki/Public_holidays_in_the_Netherlands

**Comment by svendiedrichsen** [comment]
Thank you.
