### ISSUE TITLE
Jollyday failing in OSGI-Environments with a 1.8 JRE

### ISSUE THREAD

**Issue by andy-d2019** [svendiedrichsen/jollyday#71]
We use jollyday 0.5.4 in our Apache-Camel Routes on an Apache Servicemix/Karaf, this requires threeten-extra 1.3.2, which is supposed to run with a 1.8 JRE, but wrongly declares a dependency on Java-1.9 in its OSGI headers.

https://github.com/ThreeTen/threeten-extra/issues/97

This bug has been fixed in Threeten-Extra 1.3.2, but a modified version has not been released yet.

A jollyday release with an updated version of threeten-extra would fix this issue.

**Comment by svendiedrichsen** [comment]
Version 0.5.7 release using updated dependency version.
