### ISSUE TITLE
Missing holiday for german state hessen/hessia

### ISSUE THREAD

**Issue by andy-d2019** [svendiedrichsen/jollyday#75]
The easter-sunday should be counted as a holiday in the german states Brandenburg and Hessen, but jollyday only counts it for Brandenburg.

**Comment by thackel** [comment]
Interesting topic :-)

In wikipedia they wrote:

> * für Hessen kann keine sinnvolle Angabe gemacht werden, da alle Sonntage als gesetzliche Feiertage gelten

https://de.wikipedia.org/wiki/Gesetzliche_Feiertage_in_Deutschland#%C3%9Cbersicht_aller_gesetzlichen_Feiertage

**Comment by svendiedrichsen** [comment]
The official website of Hesse's ministry of internal affairs and sports does not state easter sunday to be an official holiday: https://innen.hessen.de/buerger-staat/gesetzliche-feiertage

Please see the section _Service_ on the right hand side.

**Comment by andy-d2019** [comment]
Removing them from Brandenburg is imho not a sensible option, as they are still official holidays and thus valid information would be lost. 
E.g the use case im using jolliday for requires knowing when a holiday is irregardless of it being a sunday.

I was imho wrong in the case of easter sunday for hessia though after reading the sources you guys provided.

**Comment by svendiedrichsen** [comment]
@andy-d2019 This can be closed than?

**Comment by svendiedrichsen** [comment]
@andy-d2019 I wouldn't do that.
