### ISSUE TITLE
Init HolidayManager by Locale behaves different, depending on Locale.getDefault()

### ISSUE THREAD

**Issue by MarkFried** [svendiedrichsen/jollyday#76]
See following snippet:

		ManagerParameter parameters = ManagerParameters.create(Locale.GERMAN);
		HolidayManager mgr = HolidayManager.getInstance(parameters);

		Set<Holiday> holidays = mgr.getHolidays(2018);

The resulting set is correct as long as the default locale of the system is GERMAN, but wrong as soon as it is run with a different system/default locale.

The result should always be the german holidays regardless of the system's locale.

**Comment by svendiedrichsen** [comment]
I will look into this. Thanks.

**Comment by svendiedrichsen** [comment]
The method `ManagerParameters.create(Locale.GERMAN)` can't find a country from the provided Locale. It subsequently uses the system default locale. You could fix this by using `Locale.GERMANY` or the the class `HolidayCalendars.GERMANY`. I will make the code fall back to the language.
