### ISSUE TITLE
Austrian holidays

### ISSUE THREAD

**Issue by dwuehrer** [svendiedrichsen/jollyday#84]
Hello,

this is a bit complicated.

The resource file for Austrian holidays
https://github.com/svendiedrichsen/jollyday/blob/master/src/main/resources/holidays/Holidays_at.xml
lists Christmas Eve (24 Dec) and New Years Eve (31 Dec) as official holidays.

However:
https://www.arbeiterkammer.at/beratung/arbeitundrecht/Arbeitszeit/ArbeitszeitundRuhepausen/Feiertagsruhe.html#heading_Diese_Feiertage_stehen_allen_Beschaeftigten_zu

They are not official holidays.
Although most collective labour agreements treat them as half a work day each.

I think that their HolidayType should return false for isOfficialHoliday().

Will you consider changing them?

**Comment by svendiedrichsen** [comment]
Sure. I'm actually not an expert on the holiday subject. Especially not when it comes to holidays abroad.

**Comment by dwuehrer** [comment]
Great! Thank you.

**Comment by svendiedrichsen** [comment]
Merged your PR. Thank you.
