### ISSUE TITLE
US Holidays XML

### ISSUE THREAD

**Issue by meingraham** [svendiedrichsen/jollyday#89]
I inspected the XML file for the US Holidays over on the SourceForge page. Some of the Federal holidays need to be updated. I am happy to make the updates... but I don't know where... or how. Now that the code is here on GitHub, have the holidays files moved too? If so, I did not locate them. If the XML is still over on SourceForge, how do I provide updates? I could download the XML and make the necessary edits and post the update back. I just want to ensure that I grab the latest contributed XML and that I know how/where to make the updates.

Cheers!

Mike

**Comment by svendiedrichsen** [comment]
Hi Mike,
the whole project has moved to github. Including the holiday xml files. To fix the the US holidays you can fork this repo and create a branch on your fork. There you can fix the holidays and fix/create tests for it. After you have done this you can commit and push your changes to your repo and create a pull request. I will have a look and merge it afterwards.

Thanks in advance.
Cheers, Sven
