### ISSUE TITLE
Slovenian holiday removed

### ISSUE THREAD

**Issue by provincjalc** [svendiedrichsen/jollyday#9]
Hi,

Slovenia (si) has removed 2.may as holliday. Holliday was remove last year.

jollyday/src/main/resources/holidays/Holidays_si.xml

Greetings

**Comment by provincjalc** [comment]
Sorry,

2.may is still holliday. 2. january is not holiday anymore.

Greetings

**Comment by svendiedrichsen** [comment]
Fixed. Thanks for the info.
