### ISSUE TITLE
Pentecost (Pinksteren) is missing in the NL holiday xml

### ISSUE THREAD

**Issue by bbottema** [svendiedrichsen/jollyday#96]
[Pentecost (Pinksteren)](https://en.wikipedia.org/wiki/Pinkster) is missing in the NL holiday xml. That is every Sunday before Whit monday (sometimes called Whitsunday), Whit monday being the second day of Pentacost.

**Comment by svendiedrichsen** [comment]
Will be fixed in 0.5.8.
